### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by dee-y** [hacktivist123/VotePush#1]
Hello, am a graphic designer and i love contributing to open source projects. If you will allow, i would love to create a logo for your git page and project page. It's free of course.

**Comment by dee-y** [comment]
Alright... I will have a design for you soon

**Comment by hacktivist123** [comment]
Awesome, thanks

**Comment by dee-y** [comment]
Hi there, what do you think of this design? Did i hit the mark?

![votepush final3-06](https://user-images.githubusercontent.com/36637989/45190274-0f081980-b235-11e8-9a1c-261a522f2a8b.png)

![votepush final2](https://user-images.githubusercontent.com/36637989/45190283-18918180-b235-11e8-8845-080fc6c438f0.png)

**Comment by hacktivist123** [comment]
I love this, but I prefer the white coloured one

**Comment by dee-y** [comment]
Am glad you like it. What sizes of the logo would you like me to export for you? Or do i export in universal standard sizes. I would also export the editable .SVG/.PSD versions  for you as well as logo license.

**Comment by hacktivist123** [comment]
Universal standard sizes would be fine,  and the rest are all fine too

**Comment by dee-y** [comment]
I have made a pull request here https://github.com/hacktivist123/VotePush/pull/2
